### ISSUE TITLE
document SSN gets sent as *****

### ISSUE THREAD

**Issue by timmyimprint** [alloy-samples/quickstart-app#16]
using the sample data on the app, I get this error:
`
  "status_code": 400,
  "error": {
    "minor_code": 4002,
    "type": "Request Body Validation Failure",
    "message": "Your request body contained invalid field(s)",
    "details": {
      "message": "\"document_ssn\" with value \"&#x2a;&#x2a;&#x2a;-&#x2a;&#x2a;-1111\" fails to match the required pattern: /^\\d{9}$/",
      "path": "persons.0.document_ssn",
      "type": "string.regex.base",
      "context": {
        "pattern": {},
        "value": "***-**-1111",
        "key": "document_ssn"
      }
    },
    "error_token": "f60c9e35-aecd-4130-a171-d83d5d9c6e62"
  },
  "timestamp": 1677721145254,
  "evaluation_token": null,
  "entity_token": null,
  "application_token": "m5sJfrSg5VDocEqbolv9ohHGkhyYTeTA",
  "application_version_id": null
}`

**Comment by DBCintron** [comment]
there's a PR linked in progress to resolve, but to unblock locally you can simply remove the mask and formatting at SSN on `pages/index.tsx`

**Before change**
```
          <FieldSet>
              <Label htmlFor="ssn">SSN</Label>
              <Input
                type={"text"}
                id={"ssn"}
                value={mask(format(ssn))}
                onChange={(e) => {
                  setSSN(e.currentTarget.value);
                }}
              />
            </FieldSet>
```

**With change**
```
          <FieldSet>
              <Label htmlFor="ssn">SSN</Label>
              <Input
                type={"text"}
                id={"ssn"}
                value={ssn}
                onChange={(e) => {
                  setSSN(e.currentTarget.value);
                }}
              />
            </FieldSet>
```

**Comment by mrestuccia** [comment]
Issue has been resolved. Thanks for the feedback
